name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build XCFrameworks
    runs-on: macos-latest

    steps:
      - name: Build XCFrameworks
        working-directory: Scripts
        run: |
            ./build_eureka.sh
